stages:
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:helm2-argo
      version: 0.7.2
      name: helm2-argo
      targetNamespace: default
timeout: 60
notification: {}
