stages:
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-27c2x:helmstuff-chartmuseum
      version: 2.3.1
      name: testing
      targetNamespace: default
timeout: 60
notification: {}
