stages:
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-chartmuseum
      version: 2.3.1
      name: helm2-chartmuseum
      targetNamespace: default
timeout: 60
notification: {}
